DROP TABLE IF EXISTS TBL_PLANTS;
 
CREATE TABLE TBL_PLANTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  common_name VARCHAR(250) NOT NULL,
  scientific_name VARCHAR(250) NOT NULL,
  family VARCHAR(250) DEFAULT NULL
);